# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dnyanu\PycharmProjects\details\add.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
import mysql as mdb
from product import *
# from product import Ui_abc


class Ui_MainWindow(object):
    def HOME(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_abc()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()

    def alertmsg(self, title, Message):
        warn = QtWidgets.QMessageBox()
        warn.setIcon(QtWidgets.QMessageBox.Information)
        warn.setWindowTitle(title)
        warn.setText(Message)
        warn.setStandardButtons(QtWidgets.QMessageBox.Ok)
        warn.setWindowIcon(QtGui.QIcon('erroe.png'))
        warn.exec_()

    def ok(self, title, Message):
        ok1 = QtWidgets.QMessageBox()
        ok1.setIcon(QtWidgets.QMessageBox.Information)
        ok1.setWindowTitle(title)
        ok1.setText(Message)
        ok1.setStandardButtons(QtWidgets.QMessageBox.Ok)
        ok1.setWindowIcon(QtGui.QIcon('ok.png'))
        ok1.exec_()


    def CLR(self):
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
    def add(self):
        v =self.lineEdit.text()
        v1 =self.lineEdit_2.text()
        v2 =self.lineEdit_3.text()
        self.lineEdit_3.setValidator(QtGui.QIntValidator())
        v3 =self.lineEdit_4.text()
        self.lineEdit_4.setValidator(QtGui.QIntValidator())
        # print(v,v1,v2,v3)
        # val=(v,v1,v2,v3)
        mydb=mysql.connector.connect(host="localhost",user="root",password="root",database="testapp")
        cursor= mydb.cursor()
        aaa = "INSERT INTO  `pro` (pid,pno,cost,qty) VALUES (%s,%s,%s,%s)"
        val = (v, v1, v2, v3,)

        if v == "" or v == "null" or v1 == "" or v1 == "Null" or v2 == "" or v2 == "Null" or v3 == "" or v3 == "null":
            (self.alertmsg("error", "please fill all the product information"))

        else:
            cursor.execute(aaa, val,)
            mydb.commit()
            cursor.close()
            mydb.close()
            (self.ok("Successfull", "Added"))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(140, 20, 461, 421))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(80, 20, 321, 31))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 100, 121, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 150, 151, 61))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(80, 210, 141, 61))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(120, 260, 81, 41))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(220, 120, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 170, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 230, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 270, 113, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(170, 320, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 380, 93, 28))
        self.pushButton_2.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 320, 93, 28))
        self.pushButton_3.setObjectName("PushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.add)
        self.pushButton_2.clicked.connect(self.HOME)
        self.pushButton_3.clicked.connect(self.CLR)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Add New Entries</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Prodict ID</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Product Name</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Product Cost</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Quantiy</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "type ID here...."))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "type Name here...."))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "cost"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "quantity"))
        self.pushButton.setText(_translate("MainWindow", "ADD"))
        self.pushButton_2.setText(_translate("MainWindow", "HOME"))
        self.pushButton_3.setText(_translate("MainWindow", "RESET"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
