# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dnyanu\PycharmProjects\details\delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from product import *
import mysql as mdb
# from PyQt5.QtWidgets import QApplication,QWidget,QLabel
from PyQt5.QtGui import *
from PyQt5.QtCore import *
# from PyQt5.QtGui import *
from PyQt5.QtWidgets import *




class Ui_delete(object):

    def HOME(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_abc()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()
    def alertmsg(self, title, Message):
        warn = QtWidgets.QMessageBox()
        warn.setIcon(QtWidgets.QMessageBox.Information)
        warn.setWindowTitle(title)
        warn.setText(Message)
        warn.setStandardButtons(QtWidgets.QMessageBox.Ok)
        warn.setWindowIcon(QtGui.QIcon('erroe.png'))
        warn.exec_()

    def ok(self, title, Message):
        ok1 = QtWidgets.QMessageBox()
        ok1.setIcon(QtWidgets.QMessageBox.Information)
        ok1.setWindowTitle(title)
        ok1.setText(Message)
        ok1.setStandardButtons(QtWidgets.QMessageBox.Ok)
        ok1.setWindowIcon(QtGui.QIcon('ok.png'))
        ok1.exec_()
    def delete(self):
        a = self.lineEdit.text()

        # print(a, "Deleted")

        mydb = mysql.connector.connect(host="localhost", user="root", password="root", database='testapp')
        cursor = mydb.cursor()
        # for pid in ('pro'):
        #     aaa = "DELETE FROM `pro` WHERE pid = %s"
        #     cursor.execute(aaa,(pid,))
        if a=="" or a== "null":
            (self.alertmsg("error", "Please Enter ID"))
        else:
            cursor.execute(aaa, (a,))
            mydb.commit()
            cursor.close()
            mydb.close()
            (self.ok("Successfull", "Deleted"))

    def setupUi(self, MainWindow):
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(270, 170, 181, 61))
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 270, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 350, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.delete)
        self.pushButton_2.clicked.connect(self.HOME)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Product ID here"))
        self.pushButton.setText(_translate("MainWindow", "DELETE "))
        self.pushButton_2.setText(_translate("MainWindow", "HOME "))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_delete()
    # window = Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
