# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dnyanu\PycharmProjects\details\table.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
import mysql as mdb
import sys
# import ast

class viewdata(object):
    def viewdata(self):
        try:

            mydb= mysql.connector.connect(host="localhost",user="root",password="root",database="testapp")
            cursor = mydb.cursor()
            cursor.execute("select pid,pno,cost,qty from pro ")
            row = cursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(row):
                self.tableWidget.insertRow(row_number)
                for col_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, col_number, QtWidgets.QTableWidgetItem(str(data)))
            mydb.commit()
            cursor.close()
            mydb.close()
        except Exception as e:
            print("Err=" + e.args[0])
            tb = sys.exc_info()[2]
            print(tb.tb_lineno)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(582, 240)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 581, 241))
        self.tableWidget.setRowCount(20)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):

            _translate = QtCore.QCoreApplication.translate
            Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
            item = self.tableWidget.horizontalHeaderItem(0)
            item.setText(_translate("Dialog", "pid"))
            item = self.tableWidget.horizontalHeaderItem(1)
            item.setText(_translate("Dialog", "pno"))
            item = self.tableWidget.horizontalHeaderItem(2)
            item.setText(_translate("Dialog", "cost"))
            item = self.tableWidget.horizontalHeaderItem(3)
            item.setText(_translate("Dialog", "qty"))
            # self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">PRODUCTS</span></p></body></html>"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = viewdata()
    ui.setupUi(Dialog)
    ui.viewdata()
    Dialog.show()
    sys.exit(app.exec_())
