# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dnyanu\PycharmProjects\details\update.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
import mysql as mdb
from product import *

class Ui_update(object):

    def HOME(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_abc()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()

    def alertmsg(self, title, Message):
        warn = QtWidgets.QMessageBox()
        warn.setIcon(QtWidgets.QMessageBox.Information)
        warn.setWindowTitle(title)
        warn.setText(Message)
        warn.setStandardButtons(QtWidgets.QMessageBox.Ok)
        warn.setWindowIcon(QtGui.QIcon('erroe.png'))
        warn.exec_()
    def ok(self, title, Message):
        ok1 = QtWidgets.QMessageBox()
        ok1.setIcon(QtWidgets.QMessageBox.Information)
        ok1.setWindowTitle(title)
        ok1.setText(Message)
        ok1.setStandardButtons(QtWidgets.QMessageBox.Ok)
        ok1.setWindowIcon(QtGui.QIcon('ok.png'))
        ok1.exec_()


    def update(self):
        b=self.lineEdit.text()
        b1=self.lineEdit_2.text()

        # print("Name",b,"is update in Product_ID",b1)


        mydb = mysql.connector.connect(host="localhost", user="root", password="root", database='testapp')
        cursor = mydb.cursor()
        sql = "UPDATE pro SET pno = %s WHERE pid = %s"
        # val=(b,b1,)
        # cursor.execute(sql,(b,b1))
        # mydb.commit()
        # cursor.close()
        # mydb.close()
        if b == "" or b == "null" or b1=="" or b1=="null":
            (self.alertmsg("error", "Fields Should Not be Empty"))
        else:
            cursor.execute(sql,(b1, b,))
            mydb.commit()
            cursor.close()
            mydb.close()
            (self.ok("Successfull","Updated"))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 280, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 350, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 200, 191, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(370, 200, 171, 51))
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.update)
        self.pushButton_2.clicked.connect(self.HOME)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "UPDATE"))
        self.pushButton_2.setText(_translate("MainWindow", "HOME"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Write productID here"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Write new UPDATE here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_update()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
